ktor:
  deployment:
    host: "$API_HOST:localhost"
    port: "$API_PORT:8080"
  application:
    modules:
      - com.github.projektmagma.magmaquiz.server.ApplicationKt.mainModule

database:
  host: "$DB_HOST:localhost"
  port: "$DB_PORT:5432"
  user: "$DB_USER:postgres"
  password: "$DB_PASSWORD:"
  database: "$DB_DATABASE:"

mailer:
  displayed_name: "$MAILER_DISPLAYED_NAME"
  email: "$MAILER_EMAIL"
  support_email: "$MAILER_SUPPORT_EMAIL"
  host: "$MAILER_HOST"
  port: "$MAILER_PORT"
  password: "$MAILER_PASSWORD"
  language: "pl"